# Generated by Django 5.0.14 on 2025-11-03 22:11

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('position_fen', models.CharField(help_text='Starting position FEN', max_length=255, validators=[core.models.validate_fen])),
                ('current_fen', models.CharField(help_text='Current position FEN', max_length=255, validators=[core.models.validate_fen])),
                ('moves_pgn', models.TextField(blank=True, default='', help_text='Game moves in PGN format')),
                ('current_turn', models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=5)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('draw', 'Draw'), ('resigned', 'Resigned')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('draw', 'Draw')], help_text='Winner of the game (white, black, or draw)', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this lesson is visible and accessible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Teacher who created this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this topic is visible and accessible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.lesson')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(help_text='FEN notation of the position', max_length=255, validators=[core.models.validate_fen])),
                ('description', models.TextField(help_text='Explanation of the position or what to learn')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_sequence_part', models.BooleanField(default=False, help_text='Is this position part of a move sequence?')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this position is visible and accessible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.topic')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.PositiveIntegerField()),
                ('move_san', models.CharField(help_text='Move in Standard Algebraic Notation', max_length=10)),
                ('fen_after_move', models.CharField(help_text='Board position after this move', max_length=255, validators=[core.models.validate_fen])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.game')),
            ],
            options={
                'verbose_name': 'Game Move',
                'verbose_name_plural': 'Game Moves',
                'ordering': ['move_number'],
                'unique_together': {('game', 'move_number')},
            },
        ),
        migrations.CreateModel(
            name='PositionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(help_text='Order of this move in the sequence')),
                ('move_san', models.CharField(help_text='Move in Standard Algebraic Notation (e.g., Nf3, e4)', max_length=10)),
                ('explanation', models.TextField(help_text='Explanation of why this move is played')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='core.position')),
            ],
            options={
                'verbose_name': 'Position Sequence',
                'verbose_name_plural': 'Position Sequences',
                'ordering': ['sequence_order'],
                'unique_together': {('position', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_positions', models.ManyToManyField(blank=True, related_name='completed_by_users', to='core.position')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
