# Generated by Django 5.0.14 on 2025-11-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionsequence',
            options={'ordering': ['sequence_order', 'variation_number'], 'verbose_name': 'Position Sequence', 'verbose_name_plural': 'Position Sequences'},
        ),
        migrations.AlterUniqueTogether(
            name='positionsequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='positionsequence',
            name='parent_move',
            field=models.ForeignKey(blank=True, help_text='Parent move for variation branches. Null for main line.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='core.positionsequence'),
        ),
        migrations.AddField(
            model_name='positionsequence',
            name='variation_number',
            field=models.PositiveIntegerField(default=0, help_text='Variation number at this level (0 for main line)'),
        ),
        migrations.AlterUniqueTogether(
            name='positionsequence',
            unique_together={('position', 'parent_move', 'sequence_order', 'variation_number')},
        ),
    ]
